// <auto-generated />
using BackEnd.Repository.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(EntityFrameworkFotoContext))]
    [Migration("20201126154902_TesteMigration")]
    partial class TesteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BackEnd.Model.Foto", b =>
                {
                    b.Property<string>("uuid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("favorita");

                    b.HasKey("uuid");

                    b.ToTable("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
